title: SynthAIr Project
description: >- 
  SynthAIr is a project that aims to create synthetic aircraft data for training machine learning models.
baseurl: "" # Empty because root is the publishing source
url: "https://synthair.github.io" # Your site's URL

markdown: kramdown

# Paths to theme files
includes_dir: themes/minimal/_includes
layouts_dir: themes/minimal/_layouts
sass:
  load_paths:
    - themes/minimal/_sass
