title: SynthAIr Project
description: >
  SynthAIr is a project that aims to create synthetic aircraft data for training machine learning models.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://synthair.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Paths to theme files
includes_dir: themes/minimal/_includes
layouts_dir: themes/minimal/_layouts
sass:
  load_paths:
    - themes/minimal/_sass
