title: "SynthAIr"
description: "Improved ATM Automation and Simulation through AI-based Universal Models for Synthetic Data Generation."
theme: just-the-docs
url: "https://synthair.github.io"
baseurl: ""

# Site branding
logo: "/figures/synthair_logo.png"
favicon_ico: "/figures/synthair_icon.ico"

# Social links
github_username: SynthAIr


# Navigation structure
nav:
  - title: "Models"
    url: /models/
  - title: "Embeddings"
    url: /embeddings/
  - title: "Use Cases"
    url: /use-cases/
  - title: "Results"
    url: /results/
  - title: "Repositories"
    url: /repositories/
  - title: "Research Outputs"
    url: /research-outputs/

footer_content: "© 2025 - SynthAIr"
