title: SynthAIr Project
logo: /docs/logo.png
description: SynthAIr is a project that aims to create synthetic aircraft data for training machine learning models.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal