title: "SynthAIr"
description: "Improved ATM Automation and Simulation through AI-based Universal Models for Synthetic Data Generation."
theme: just-the-docs
url: "https://synthair.github.io"
baseurl: ""

# Site branding
logo: "/figures/synthair_logo.png"
favicon_ico: "/figures/synthair_icon.ico"

# Social links
github_username: SynthAIr

# EU Funding Acknowledgement
funding_acknowledgement: "This project has received funding from the SESAR 3 Joint Undertaking under grant agreement No 101114847, part of the European Union’s Horizon 2020 research and innovation programme."

# Navigation structure
nav:
  - title: "About"
    url: /about/
  - title: "Models"
    url: /models/
  - title: "Embeddings"
    url: /embeddings/
  - title: "Use Cases"
    url: /use-cases/
  - title: "Results"
    url: /results/
  - title: "Repositories"
    url: /repositories/
  - title: "Publications"
    url: /publications/

footer_content: "© 2025 - SynthAIr Consortium. All rights reserved. Licensed to SESAR 3 Joint Undertaking under conditions.."
